In [1]:
import plasticity

In [2]:
from pylab import *

In [5]:
idx=r_[0:sz]

In [4]:
N=4
sz=100
rates=[10,40]

In [6]:
idx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
sq_sz=sz/N

In [8]:
sq_sz

25

In [9]:
l=[]

In [10]:
for i in range(N):
        
    
        r=ones(idx.shape)*rates[0]
        r[((sq_sz*i)<=idx) & (idx<(sq_sz*(i+1)))]=rates[1]
        
        l.append(r)

In [11]:
l

[array([ 40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.]),
 array([ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  4

In [14]:
a=array(l,numpy.float)

In [13]:
import numpy

In [15]:
a

array([[ 40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.],
       [ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,
         10.,  10.,  10.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,  40.,
         40.,  40.,  40

In [17]:
a.shape

(4, 100)

In [18]:
display=True

In [19]:
for r in a:
            plot(r)

In [20]:
def make_square(N=4,sz=100,rates=[10,40],display=False):
    
    idx=r_[0:sz]
    
    sq_sz=sz/N
    l=[]
    for i in range(N):
        
    
        r=ones(idx.shape)*rates[0]
        r[((sq_sz*i)<=idx) & (idx<(sq_sz*(i+1)))]=rates[1]
        
        l.append(r)
        
    a=array(l,numpy.float)
        
    if display:
        
        for r in a:
            plot(r)
    
    
    return a

In [21]:
num_patterns=10
    N=100
    rates=make_square(num_patterns,N,[1,50])
    data={'im':[rates],'im_scale_shift':[1.0,0.0]}  

IndentationError: unexpected indent (<ipython-input-21-f0d65324b859>, line 2)

In [22]:
    num_patterns=10
    N=100
    rates=make_square(num_patterns,N,[1,50])
    data={'im':[rates],'im_scale_shift':[1.0,0.0]}   

In [23]:
rates

array([[ 50.,  50.,  50.,  50.,  50.,  50.,  50.,  50.,  50.,  50.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,  50.,
         50.,  50.,  50.,  50.,  50.,  50.,  50.,  50.,  50.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1

In [24]:
plasticity.utils.zpickle.save(data,'square10.dat')

In [25]:
import h5py

In [26]:
data2 = hf.get('../fromBrian/new_images12_dog.hdf5')

NameError: name 'hf' is not defined

In [27]:
with h5py.File('../fromBrian/new_images12_dog.hdf5','r') as hf:
    print('List of arrays in this file: \n', hf.keys())


('List of arrays in this file: \n', [u'image0', u'image1', u'image10', u'image11', u'image2', u'image3', u'image4', u'image5', u'image6', u'image7', u'image8', u'image9'])


In [32]:
with h5py.File('../fromBrian/new_images12_dog.hdf5','r') as hf:
    print('List of arrays in this file: \n', hf.keys())
    data2 = hf.get('image1')
    np_data = np.array(data2)

('List of arrays in this file: \n', [u'image0', u'image1', u'image10', u'image11', u'image2', u'image3', u'image4', u'image5', u'image6', u'image7', u'image8', u'image9'])


In [33]:
np_data.shape

(236, 236)

In [34]:
im0 = np.array(hf.get('image0'))

ValueError: Not a location (Invalid object id)

In [49]:
with h5py.File('../fromBrian/new_images12_dog.hdf5','r') as hf:
    print('List of arrays in this file: \n', hf.keys())
    for x in range(12):
        im = np.array(hf.get('image' + str(x)))
        scipy.misc.imsave('im' + str(x) + '.png', im)

('List of arrays in this file: \n', [u'image0', u'image1', u'image10', u'image11', u'image2', u'image3', u'image4', u'image5', u'image6', u'image7', u'image8', u'image9'])


In [37]:
im0.shape

(236, 236)

In [38]:
import matplotlib

In [39]:
matplotlib.image.imsave('im0.png', im0)

In [42]:
import scipy.misc

In [43]:
scipy.misc.imsave('im0.png', im0)

In [50]:
m1 = numpy.random.random(size = (256,256))
m2 = numpy.random.random(size = (256,256))
 
with h5py.File('data.hdf5', 'w') as hf:
    hf.create_dataset('image0', data=m1)
    hf.create_dataset('image1', data=m2)

In [51]:
with h5py.File('../inputFormat/noise_images.hdf5','r') as hf:
    print('List of arrays in this file: \n', hf.keys())
        

('List of arrays in this file: \n', [u'image0', u'image1'])


In [52]:
im.shape

(236, 236)

In [53]:
np.max(im)

59992

In [54]:
np.min(im)

0

In [56]:
np.min(m1)

5.7734024954902985e-05

In [60]:
f=h5py.File('../inputFormat/new_images12_dog.hdf5','r')

In [61]:
list(f.attrs['im_scale_shift'])

[0.00019421402359941087, -6.4006234452517239]

In [75]:
var = {}
var['im_scale_shift'] = [1,0]
var['im']=[]
var['im'].append(m1)
var['im'].append(m2)

In [76]:
var

{'im': [array([[ 0.57190661,  0.04365721,  0.57750737, ...,  0.54185132,
           0.35661939,  0.8623524 ],
         [ 0.83313072,  0.08749367,  0.27695579, ...,  0.25917624,
           0.25039423,  0.28014748],
         [ 0.09982197,  0.78962775,  0.58478191, ...,  0.20505921,
           0.76283482,  0.44360937],
         ..., 
         [ 0.99596105,  0.2732793 ,  0.63605191, ...,  0.75421189,
           0.37621459,  0.38613036],
         [ 0.74964262,  0.26764265,  0.85664257, ...,  0.24968845,
           0.53873145,  0.98523642],
         [ 0.46213082,  0.43557346,  0.26833627, ...,  0.96636033,
           0.16044697,  0.70499971]]),
  array([[ 0.22473151,  0.13048069,  0.50067297, ...,  0.68692957,
           0.35646117,  0.72938332],
         [ 0.11002257,  0.85351722,  0.28436073, ...,  0.69787996,
           0.31719458,  0.43851528],
         [ 0.27653682,  0.87790384,  0.03567628, ...,  0.39077316,
           0.41991117,  0.53070508],
         ..., 
         [ 0.01279937,  0.

In [64]:
var['im'][0]= m1

KeyError: 'im'

In [72]:
hdf5_save_images(var,'testimageshpdf5')

NameError: name 'hdf5_save_images' is not defined

In [77]:
    f=h5py.File('testimages.hdf5','w')

    f.attrs['im_scale_shift']=var['im_scale_shift']
    for i,im in enumerate(var['im']):
        f.create_dataset('image%d' % i,data=im)

    f.close()